### ISSUE TITLE
Install does not work with composer 2.. please upgrade npm-bridge

### ISSUE THREAD

**Issue by nileshd** [xpersonas/laravel-styleguide#36]
Package does not install with composer2, as npm-bridge 4.1.0 is locked to composer1.0.

npm-bridge 5.0 uses composer 2.. Please update the dependencies if possible.

 Problem 1
    - xpersonas/laravel-styleguide[v1.0.0, ..., v1.0.16] require eloquent/composer-npm-bridge ^4.1 -> satisfiable by eloquent/composer-npm-bridge[4.1.0].
    - eloquent/composer-npm-bridge 4.1.0 requires composer-plugin-api ^1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires xpersonas/laravel-styleguide ^1.0 -> satisfiable by xpersonas/laravel-styleguide[v1.0.0, ..., v1.0.16].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by xpersonas** [comment]
Fixed in latest PR. Thanks!

**Comment by nileshd** [comment]
Thank you!
